apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinatra
  labels: 
    app.kubernetes.io/name: sinatra
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sinatra
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sinatra
    spec:
      containers:
      - name: sinatra
        image: docker.io/ig3lk0tt/sinatra-sample:latest
        ports:
        - containerPort: 4567
          name: http
          protocol: TCP
          
