apiVersion: v1
kind: Service
metadata:
  name: sinatra-service
  labels:
    app.kubernetes.io/name: sinatra
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: sinatra
  ports:
    #Cluster port
  - port: 8080
    #Pod port
    targetPort: 4567
    #Exposed port on host
    nodePort: 30000
