apiVersion: v1
kind: Service
metadata:
  name: sinatra-service
  labels:
    app.kubernetes.io/name: sinatra
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sinatra
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 4567
